name: ml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.11
  - pip=21.0.1
  - pip:
      - scikit-learn==0.23.2
      - scikit-optimize==0.8.1
      - tensorboard==2.9.0
      - tensorflow==2.9.0
      - keras==2.9.0
      - tensorflow-datasets==4.6.0
      - protobuf==3.19.4
      - pandas==1.1.4
      - pyyaml==5.3.1
      - scipy==1.5.4
      - h5py==2.10.0
      - lightgbm==3.2.1
      - xgboost==1.3.1
      - scikit-optimize==0.8.1
      - seaborn==0.11.1